/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pares3;

/**
 *
 * @author david
 */
public class frmpares extends javax.swing.JFrame {

    /**
     * Creates new form frmpares
     */
    int vecnumeros[];
    int contador;
    int aleatorio;
    int cartas;
    int valor1,valor2;
    int contadorclick;
    int nboton;
    
    public frmpares() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btnrestart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btn1.setText("jButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(20, 40, 73, 23);

        btn2.setText("jButton2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(110, 40, 73, 23);

        btn3.setText("jButton3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(210, 40, 73, 23);

        btn4.setText("jButton4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(300, 40, 73, 23);

        btn5.setText("jButton1");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(20, 80, 73, 23);

        btn6.setText("jButton2");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(110, 80, 73, 23);

        btn7.setText("jButton3");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(210, 80, 73, 23);

        btn8.setText("jButton4");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(300, 80, 73, 23);

        btn9.setText("jButton1");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(20, 120, 73, 23);

        btn10.setText("jButton2");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(110, 120, 73, 23);

        btn11.setText("jButton3");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11);
        btn11.setBounds(210, 120, 73, 23);

        btn12.setText("jButton4");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12);
        btn12.setBounds(300, 120, 73, 23);

        btn13.setText("jButton1");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13);
        btn13.setBounds(20, 160, 73, 23);

        btn14.setText("jButton2");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        getContentPane().add(btn14);
        btn14.setBounds(110, 160, 73, 23);

        btn15.setText("jButton3");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        getContentPane().add(btn15);
        btn15.setBounds(210, 160, 73, 23);

        btn16.setText("jButton4");
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        getContentPane().add(btn16);
        btn16.setBounds(300, 160, 73, 23);

        btnrestart.setText("restart");
        btnrestart.setMaximumSize(new java.awt.Dimension(73, 23));
        btnrestart.setMinimumSize(new java.awt.Dimension(73, 23));
        btnrestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestartActionPerformed(evt);
            }
        });
        getContentPane().add(btnrestart);
        btnrestart.setBounds(160, 200, 80, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         btn1.setText("");
         btn2.setText("");
         btn3.setText("");
         btn4.setText("");
         btn5.setText("");
         btn6.setText("");
         btn7.setText("");
         btn8.setText("");
         btn9.setText("");
         btn10.setText("");
         btn11.setText("");
         btn12.setText("");
         btn13.setText("");
         btn14.setText("");
         btn15.setText("");
         btn16.setText("");

        while(contador<=14)
        {
            aleatorio=(int)(Math.random()*16);
            if(vecnumeros[aleatorio]==0)
            {
               vecnumeros[aleatorio]=cartas;
               contador+=1;
               cartas+=1;
               if(cartas>7)
               {
                   cartas=0;
               }
            }
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        btn1.setText(String.valueOf(vecnumeros[0]));
        contadorclick++;
        int nbtn=1;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn1.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn1.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn1.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn1.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }
        }
        else
        {
            btn1.setEnabled(true);
            btn1.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        btn2.setText(String.valueOf(vecnumeros[1]));
        contadorclick++;
        int nbtn=2;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn2.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn2.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn2.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn2.setText("");                
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn2.setEnabled(true);
            btn2.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }       
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        btn3.setText(String.valueOf(vecnumeros[2]));
        contadorclick++;
        int nbtn=3;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn3.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn3.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn3.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn3.setText("");                
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn3.setEnabled(true);
            btn3.setText("");
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        btn4.setText(String.valueOf(vecnumeros[3]));
        contadorclick++;
        int nbtn=4;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn4.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn4.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn4.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn4.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn4.setEnabled(true);
            btn4.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        btn5.setText(String.valueOf(vecnumeros[4]));
        contadorclick++;
        int nbtn=5;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn5.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn5.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn5.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn5.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn5.setEnabled(true);
            btn5.setText("");  
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        btn6.setText(String.valueOf(vecnumeros[5]));
        contadorclick++;
        int nbtn=6;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn6.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn6.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn6.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn6.setText("");  
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn6.setEnabled(true);
            btn6.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        btn7.setText(String.valueOf(vecnumeros[6]));
        contadorclick++;
        int nbtn=7;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn7.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn7.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn7.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn7.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn7.setEnabled(true);
            btn7.setText("");
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        btn8.setText(String.valueOf(vecnumeros[7]));
        contadorclick++;
        int nbtn=8;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn8.getText());                
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn8.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn8.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn8.setText("");  
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn8.setEnabled(true);
            btn8.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
         btn9.setText(String.valueOf(vecnumeros[8]));
         contadorclick++;
        int nbtn=9;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn9.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn9.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn9.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn9.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn9.setEnabled(true);
            btn9.setText("");
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        btn10.setText(String.valueOf(vecnumeros[9]));
        contadorclick++;
        int nbtn=10;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn10.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn10.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn10.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn10.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn10.setEnabled(true);
            btn10.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        btn11.setText(String.valueOf(vecnumeros[10]));
        contadorclick++;
        int nbtn=11;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn11.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn11.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn11.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn11.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }        
        }
        else
        {
            btn11.setEnabled(true);
            btn11.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        btn12.setText(String.valueOf(vecnumeros[11]));
        contadorclick++;
        int nbtn=12;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn12.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn12.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn12.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn12.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn12.setEnabled(true);
            btn12.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        btn13.setText(String.valueOf(vecnumeros[12]));
        contadorclick++;
        int nbtn=13;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn13.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn13.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn13.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn13.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn13.setEnabled(true);
            btn13.setText("");
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        btn14.setText(String.valueOf(vecnumeros[13]));
        contadorclick++;
        int nbtn=14;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn14.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn14.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn14.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn14.setText(""); 
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn14.setEnabled(true);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            btn14.setText(""); 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        btn15.setText(String.valueOf(vecnumeros[14]));
        contadorclick++;
        int nbtn=15;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn15.getText());            
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn15.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn15.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }
            }
            else
            {
                btn15.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }
            }            
        }
        else
        {
            btn15.setEnabled(true);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                } 
            btn15.setText(""); 
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        btn16.setText(String.valueOf(vecnumeros[15]));
        contadorclick++;
        int nbtn=16;
        if(contadorclick==1)
        {
            valor1=Integer.valueOf(btn16.getText());
        }
        else if (contadorclick==2)
        {
            valor2=Integer.valueOf(btn16.getText());
            nboton=nbtn;
            if(valor1==valor2)
            {
                btn16.setEnabled(false);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(false);
                    break;
                    case 2: btn2.setEnabled(false);
                    break;
                    case 3: btn3.setEnabled(false);
                    break;
                    case 4: btn4.setEnabled(false);
                    break;
                    case 5: btn5.setEnabled(false);
                    break;
                    case 6: btn6.setEnabled(false);
                    break;
                    case 7: btn7.setEnabled(false);
                    break;
                    case 8: btn8.setEnabled(false);
                    break;
                    case 9: btn9.setEnabled(false);
                    break;
                    case 10: btn10.setEnabled(false);
                    break;
                    case 11: btn11.setEnabled(false);
                    break;
                    case 12: btn12.setEnabled(false);
                    break;
                    case 13: btn13.setEnabled(false);
                    break;
                    case 14: btn14.setEnabled(false);
                    break;
                    case 15: btn15.setEnabled(false);
                    break;
                    case 16: btn16.setEnabled(false);
                    break;
                        
                }                
            }
            else
            {
                btn16.setText("");
                switch(nboton)
                {
                    case 1: btn1.setText("");
                    break;
                    case 2: btn2.setText("");
                    break;
                    case 3: btn3.setText("");
                    break;
                    case 4: btn4.setText("");
                    break;
                    case 5: btn5.setText("");
                    break;
                    case 6: btn6.setText("");
                    break;
                    case 7: btn7.setText("");
                    break;
                    case 8: btn8.setText("");
                    break;
                    case 9: btn9.setText("");
                    break;
                    case 10: btn10.setText("");
                    break;
                    case 11: btn11.setText("");
                    break;
                    case 12: btn12.setText("");
                    break;
                    case 13: btn13.setText("");
                    break;
                    case 14: btn14.setText("");
                    break;
                    case 15: btn15.setText("");
                    break;
                    case 16: btn16.setText("");
                    break;
                        
                }

            }            
        }
        else
        {
            btn16.setEnabled(true);
                switch(nboton)
                {
                    case 1: btn1.setEnabled(true);
                    btn1.setText("");
                    break;
                    case 2: btn2.setEnabled(true);
                    btn2.setText("");
                    break;
                    case 3: btn3.setEnabled(true);
                    btn3.setText("");
                    break;
                    case 4: btn4.setEnabled(true);
                    btn4.setText("");
                    break;
                    case 5: btn5.setEnabled(true);
                    btn5.setText("");
                    break;
                    case 6: btn6.setEnabled(true);
                    btn6.setText("");
                    break;
                    case 7: btn7.setEnabled(true);
                    btn7.setText("");
                    break;
                    case 8: btn8.setEnabled(true);
                    btn8.setText("");
                    break;
                    case 9: btn9.setEnabled(true);
                    btn9.setText("");
                    break;
                    case 10: btn10.setEnabled(true);
                    btn10.setText("");
                    break;
                    case 11: btn11.setEnabled(true);
                    btn11.setText("");
                    break;
                    case 12: btn12.setEnabled(true);
                    btn12.setText("");
                    break;
                    case 13: btn13.setEnabled(true);
                    btn13.setText("");
                    break;
                    case 14: btn14.setEnabled(true);
                    btn14.setText("");
                    break;
                    case 15: btn15.setEnabled(true);
                    btn15.setText("");
                    break;
                    case 16: btn16.setEnabled(true);
                    btn16.setText("");
                    break;
                        
                }          
            btn16.setText("");
            valor1=0;
            valor2=0;
            contadorclick=0;
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btnrestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestartActionPerformed
         btn1.setText("");
         btn2.setText("");
         btn3.setText("");
         btn4.setText("");
         btn5.setText("");
         btn6.setText("");
         btn7.setText("");
         btn8.setText("");
         btn9.setText("");
         btn10.setText("");
         btn11.setText("");
         btn12.setText("");
         btn13.setText("");
         btn14.setText("");
         btn15.setText("");
         btn16.setText("");

        while(contador<=14)
        {
            aleatorio=(int)(Math.random()*16);
            if(vecnumeros[aleatorio]==0)
            {
               vecnumeros[aleatorio]=cartas;
               contador+=1;
               cartas+=1;
               if(cartas>7)
               {
                   cartas=0;
               }
            }
            
        }
    }//GEN-LAST:event_btnrestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnrestart;
    // End of variables declaration//GEN-END:variables
}
